const BAD_RESOURCE_ID_FORMAT = 'BAD_RESOURCE_ID_FORMAT';
const MISSING_RESOURCE_FIELD = 'MISSING_RESOURCE_FIELD';
const RESOURCE_ID_NOT_FOUND = 'RESOURCE_ID_NOT_FOUND';
const RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND';
const INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
const INVALID_TOKEN = 'INVALID_TOKEN';
const MISSING_TOKEN = 'MISSING_TOKEN';
const UNEXPECTED_ERROR = 'UNEXPECTED_ERROR';
const MISSING_AUTHORIZATION = 'MISSING_AUTHORIZATION';

module.exports = {
  BAD_RESOURCE_ID_FORMAT,
  MISSING_RESOURCE_FIELD,
  RESOURCE_ID_NOT_FOUND,
  RESOURCE_NOT_FOUND,
  INVALID_CREDENTIALS,
  INVALID_TOKEN,
  MISSING_TOKEN,
  UNEXPECTED_ERROR,
  MISSING_AUTHORIZATION,
};
